
OBJ_PATH=../../../src/expansions/

all:
	make -C ../../../
	gcc -I ../../../libft/includes main.c ../../../src/exec/del_array.o $(OBJ_PATH)path_clever_split.o $(OBJ_PATH)pattern_quote_removal.o	$(OBJ_PATH)pathname_expansion.o ../../../libft/libft.a -o	expand
