
all:
	gcc -g str_replace.c test_str_replace.c -I . -I ../../libft/includes -L ../../libft/ -lft -o test_str_replace
	gcc -g remove_quotes.c test_remove_quotes.c -I . -I ../../libft/includes -L ../../libft/ -lft -o test_remove_quotes	
